---
kind: Service
apiVersion: v1
metadata:
  name: mainui-rolling-svc
spec:
  type: ClusterIP
  # clusterIP: 10.100.10.10
  selector:
    app: web
    version: stable
  ports:
    - port: 80
      targetPort: 8080
