---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mainui-green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
      version: green
  template:
    metadata:
      name: mainui-green-pod
      labels:
        app: web
        version: green
    spec:
      containers:
        - name: mainui-green-container
          image: whatwant/node-web:3.0
          ports:
            - containerPort: 8080
