---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mainui-blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
      version: blue
  template:
    metadata:
      name: mainui-blue-pod
      labels:
        app: web
        version: blue
    spec:
      containers:
        - name: mainui-blue-container
          image: whatwant/node-web:2.0
          ports:
            - containerPort: 8080
