---
# Deployment
kind: Deployment
apiVersion: apps/v1
metadata:
  name: adminer-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      name: adminer-pod
      labels:
        app: adminer
    spec:
      containers:
        - name: adminer-container
          image: adminer
          ports:
            - containerPort: 8080

---
# Service
kind: Service
apiVersion: v1
metadata:
  name: adminer-svc
spec:
  type: LoadBalancer
  # clusterIP: 10.100.10.10
  selector:
    app: adminer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
